### ISSUE TITLE
Vehicle Godmode Bug

### ISSUE THREAD

**Issue by InterSstellar** [NexiusTailer/Nex-AC#154] opened 2020-05-11 06:41 UTC
Hello, My Client Kicked Cuz Of God mode In Vehicle And This Was The Log
`[11/05/2020 04:10:42] [Nex-AC debug] AC veh health: 1000.000000, veh health: 1000.000000, veh: 2`
I'm 100% Sure That My Client Was Not Cheating.

He Was Using /Tune Command.
The /Tune Command Repairs The Vehicle.
He Was Escaping And I Was Shooting At His car And After He Used /Tune 3 Times At 10 Seconds He Got Kicked.

**Comment by InterSstellar** [comment] 2020-05-11 07:13
I Think It Will Fix By Just Adding `ACInfo[ac_driver][acVehDmgRes] = false;` Under `ac_fpublic ac_RepairVehicle(vehicleid)` At [This Line](https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9.52/nex-ac.inc#L1691)

**Comment by NexiusTailer** [comment] 2020-05-11 08:04
> I Think It Will Fix By Just Adding `ACInfo[ac_driver][acVehDmgRes] = false;` Under `ac_fpublic ac_RepairVehicle(vehicleid)` At [This Line](https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9.52/nex-ac.inc#L1691)

It is already gets false value when the player [is actually applying new vehicle health](https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9.52/nex-ac.inc#L4954) set by the server.

**Comment by InterSstellar** [comment] 2020-05-11 12:16
But How It Detects It As God Mode? If The Problem Is Lag There are 3 Warnings Before Kick How It Detects That As A Cheat 3 Times In 10 Seconds? =((

Any Way Its Not A Problem Maybe Its Because Of My Bad Coding Skills.
You Made A Nice AC <3
I Was Going To Have A Long Hard Time Creating An Anti Cheat Like that And I'm Pretty Sure I Can't Do That Even If I Spend A Lot Of Time.

The Only Thing Was A Little Of Editing To Make It Work With Weapon-Config.

And Sorry For My Bad English. ;D

**Comment by NexiusTailer** [comment] 2020-05-11 15:38
> But How It Detects It As God Mode? If The Problem Is Lag There are 3 Warnings Before Kick How It Detects That As A Cheat 3 Times In 10 Seconds? =((

It's not clear enough what is happening. You can provide some minimal working code example and specific steps how the problem can be reproduced (the code you use and exactly the actions you perform).

> The Only Thing Was A Little Of Editing To Make It Work With Weapon-Config.

Well, first of all you should disable all the anticheats which related to health and damage (anti-health hack onfoot, anti-armour hack, anti-godmode onfoot). The only problem that still remains after all is a quick re-spawn bug when you die in vehicle (due to vehicle explosion, for example), which triggers the corresponding anti-cheat code. You can disable anti-fake spawn as well, but it will not be a proper solution I think... (as cheaters could use fake or fast re-spawn)

**Comment by InterSstellar** [comment] 2020-05-12 04:05
> It's not clear enough what is happening. You can provide some minimal working code example and specific steps how the problem can be reproduced

3 People Were On The Vehicle Roof And Shooting The Vehicle. And The Player Was Using The /Tun Command To Repair His Vehicle

This Is My /Tun Command
`CMD:tun(playerid,params[])
{
	if (!IsPlayerInAnyVehicle(playerid)) return SCM(playerid,COLOR_ERROR,"Shoma Bayad Dar Mashin Bashid.");
	if (GetPlayerState(playerid) != PLAYER_STATE_DRIVER) return SCM(playerid,COLOR_ERROR,"Shoma Bayad Ranande Mashin Bashid.");
	if (P_tune_package[playerid] == 0) return SCM(playerid,COLOR_ERROR,"Shoma Package Tune Nadarid.");
	P_tune_package[playerid] --;
	RepairVehicle(GetPlayerVehicleID(playerid));
	TuneVeh(GetPlayerVehicleID(playerid));
	PlayerPlaySound(playerid, 1133, 0.0, 0.0, 0.0);
	format(FormatString, 144, "[Tune] %s(%d) Az Package Race Estefade Kard Baghimande: %d", P_newname[playerid], playerid, P_tune_package[playerid]);
	SCMToNearPlayers(playerid, COLOR_BLUE, FormatString, 35.0, true);
	return 1;
}`

And This Is On Player Weapon Shot
`public OnPlayerWeaponShot(playerid, weaponid, hittype, hitid, Float:fX, Float:fY, Float:fZ)
{
	switch(hittype)
	{
		case BULLET_HIT_TYPE_VEHICLE:
		{
			if (AntiCheatGetVehicleDriver(hitid) != INVALID_PLAYER_ID)
			{
				if (P_IsAFK[AntiCheatGetVehicleDriver(hitid)] != 0 || P_IsInAdminMode[AntiCheatGetVehicleDriver(hitid)] == true) return 0;
				if (GetPlayerTeam(playerid) == GetPlayerTeam(AntiCheatGetVehicleDriver(hitid)) && GetPlayerTeam(playerid) != 0xFF) return 0;
			}
		}
	}
	return 1;
}`

> Well, first of all you should disable all the anticheats which related to health and damage (anti-health hack onfoot, anti-armour hack, anti-godmode onfoot). The only problem that still remains after all is a quick re-spawn bug of weapon-config, when you die in vehicle (due to vehicle explosion, for example), which triggers the corresponding anti-cheat code. You can disable anti-fake spawn as well, but it will not be a proper solution I think... (as cheaters could use fake or fast re-spawn)

I Disabled All These Anti-Cheats before And For Anti-FakeSpawn I Defined A Var Called `s_LastTrueDeath[MAX_PLAYERS]` And I Set The Value Of It To `true` Under `OnPlayerDeath` In Weapon-Config And i Set `s_LastTrueDeath[playerid]` Value To `false` Under `OnPlayerSpawn` In My Gm. And Last Check Under `OnCheatDetected` Is This:
`switch (code)
{
	case 27:
	{
		if (s_LastTrueDeath[playerid]) return 1;
	}
}`
I Tested It And It Fixed The Problem And Cheaters Cannot Use Fake-Spawn Too.

**Comment by NexiusTailer** [comment] 2020-05-12 17:13
I can't reproduce it, unfortunately. Does the problem occur regularly or applying these actions not necessarily lead to its occurrence?

**Comment by InterSstellar** [comment] 2020-05-14 17:11
Not Always
But Sometimes It Happens When Repairing The Vehicle.

**Comment by NexiusTailer** [comment] 2020-05-14 19:22
So I still cannot get such a behaviour on the test server

**Comment by InterSstellar** [comment] 2020-05-18 14:59
Me Too But When The Server Is Running On A VPS And 20 Players Are Playing It Will Happen For Someone ;D

**Comment by NexiusTailer** [comment] 2020-05-18 15:19
Ok, can you get some short video then?..

**Comment by InterSstellar** [comment] 2020-05-19 15:18
https://streamable.com/3xioq3

**Comment by NexiusTailer** [comment] 2020-05-20 21:54
Hmm, seems to be fixed (new version including this fix will be released soon). The solution was also to reset internal gm warnings when player applies new veh health.

**Closed by NexiusTailer** 2020-05-20 21:54 UTC
