### ISSUE TITLE
Anti-Invisible hack detected with a non conventionnal connection script.

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#38] opened 2017-05-19 20:27 UTC
TO TEST:
next-ac_test-rt2.pwn:
```
//
// Nex-Ac Test Script #5(Anti-Invisible hack detected with a non conventionnal connection script)
//      by: rt-2
//      date: 2017-05-19
//
//This script will kick you if you
//      connect to the server.

// Main Libraries
#include <a_samp>
#include <crashdetect>

#include <nex-ac>

#include <YSI\y_timers>

#include <SKY>
#include <weapon-config>
#include <YSF>

public OnGameModeInit()
{

	SetGameModeText("Test Script");

	return 1;
}
public OnPlayerConnect(playerid)
{
	SetSpawnInfo(playerid, NO_TEAM, 252, 1757.00, -1946.00, 13.56, 0, 0, 0, 0, 0, 0, 0);
	SpawnPlayer(playerid);
	defer AnotherFunction(playerid);
	return 1;
}

public OnPlayerSpawn(playerid)
{
	SetPlayerPos(playerid, 1757.00, -1946.00, 13.56);
	return 1;
}

timer AnotherFunction[333](playerid)
{
	TogglePlayerSpectating(playerid, 1);
	SetCameraBehindPlayer(playerid);
	InterpolateCameraPos(playerid, 2161.4900, -964.5700, 114.8100, 2161.4900, -964.5700, 114.8100, 1000, CAMERA_MOVE);
	InterpolateCameraLookAt(playerid, 2160.6804, -965.1769, 114.6250, 2160.6804, -965.1769, 114.6250, 1000, CAMERA_MOVE);
	return 1;
}

main()
{
	print("\n----------------------------------");
	printf(" 'Nex-Ac Test Script' by rt-2 ");
	print("----------------------------------\n");
}
```
server.cfg:
```
echo Executing Server Config...
lanmode 0
rcon_password 1337
maxplayers 170
port 7778
hostname [SAARP] SA-MP 0.3 Test Server
plugins crashdetect SKY YSF
gamemode0 next-ac_test-rt2 1
filterscripts
announce 0
chatlogging 0
weburl www.sa-mp.com
onfoot_rate 40
incar_rate 40
weapon_rate 40
stream_distance 300.0
stream_rate 1000
maxnpc 120
logtimeformat [%H:%M:%S]
language English
```

I understand that you don't want to guarantee compatibility with weapon-config, but is there a way I could modify something?
Thank you,
rt-2

**Comment by NexiusTailer** [comment] 2017-05-20 20:18
Solution: include y_timers before nex-ac. To avoid hook errors also include y_hooks, so have something like this:
>#include <YSI\y_timers>
>#include <YSI\y_hooks>
>
>#include <nex-ac>

Please let me know if the problem is resolved in this way.

**Closed** 2017-06-02 12:51 UTC

**Comment by rt-2** [comment] 2017-06-02 15:33
It did not, but it doesn't matter because compatibility with weapon-config is not really a priority.

**Comment by NexiusTailer** [comment] 2017-06-13 13:17
Completely fixed in 1.9.26

**Comment by rt-2** [comment] 2017-12-10 09:23
Issue came back in 1.9.29 or 1.9.30

**Comment by NexiusTailer** [comment] 2017-12-10 12:16
I checked this and it seems the spawn doesn't have time to process, because the timer is called before OnPlayerSpawn. Try to increase the delay value:

```
timer AnotherFunction[800](playerid)
```

With this value I no longer faced this problem.

**Comment by rt-2** [comment] 2017-12-12 02:48
But before you did fix it, is there a way to revert the anticheat to that state/behavior?
Thank you,
rt-2

**Comment by NexiusTailer** [comment] 2017-12-13 19:09
If I return an old algorithm (which doesn't reset players' data in OnPlayerSpawn if the SpawnPlayer function was used), then there will be false detections when using SpawnPlayer in cases where the player isn't spawned. The class system in samp is very unpredictable in some cases, so I think it is optimal solution at the moment and I don't plan to change it in the next versions unless a better solution will be found.

**Comment by rt-2** [comment] 2018-01-27 02:47
For me "anotherFunction" is the returned of a threaded mysql query.
I will apply the equivalent of moving "defer AnotherFunction(playerid);" in "OnPlayerSPawn", so that the spectating stuff happens after you reset all variables.
rt-2
