### ISSUE TITLE
Pawn.Raknet's giving too many errors

### ISSUE THREAD

**Issue by recepilhanli** [NexiusTailer/Nex-AC#275] opened 2022-09-10 11:21 UTC
[23:41:50] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnOutgoingPacket: Array index out of bounds
[23:41:50] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[23:41:50] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[23:41:50] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[23:41:50] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds
[23:41:50] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[23:41:50] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[23:41:50] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[23:41:50] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds
[23:41:50] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds
[23:41:50] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_PASSENGER_SYNC: Array index out of bounds

When I saw these kinnda errors, server couldnt response.

**Comment by NexiusTailer** [comment] 2022-09-10 11:40
What's the version of Pawn.RakNet plugin you use?

**Comment by recepilhanli** [comment] 2022-09-10 11:42
1.5.1 the lastest version of pawn.raknet. (For SA-MP Server, not for O:MP)

**Comment by NexiusTailer** [comment] 2022-09-10 11:48
Add crashdetect plugin and re-compiler your scripts with `-d3` compilation flag, then try to reproduce this problem again. Log messages should be more detailed with mentioned plugin and you'll probably see where exactly you have out-of-bounds issue.

**Comment by recepilhanli** [comment] 2022-09-10 11:52
Thx I'll try.

**Comment by NexiusTailer** [comment] 2022-09-10 16:21
1. Go to a folder with your compiler (`pawno` folder in default server package) and create a file named "pawn.cfg" there (enable showing file extensions in explorer to make .cfg extension to it)
2. Open this file via notepad and add `-d3` there, save and close
3. Re-compile your scripts and you should see some extended compilation info when it finishes (this means you do everything right)

**Comment by recepilhanli** [comment] 2022-09-12 17:06
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public OnIncomingPacket: Array index out of bounds
[19:49:49] [Pawn.RakNet] EveryScriptImpl: AMX error occurred in public pr_ip_AC_DRIVER_SYNC: Array index out of bounds

same thing happened. Nothing changed.

Maybe we can check all variables with IsNaN method?

**Comment by NexiusTailer** [comment] 2022-09-12 17:35
> same thing happened. Nothing changed.

There must be logs from crashdetect if something really goes wrong with such type of runtime error. Re-check if you done everything right and attach full logs instead of this specific part of plugin's prints.

> Maybe we can check all variables with IsNaN method?

How this is related to listed problem?

**Comment by recepilhanli** [comment] 2022-09-16 18:10
But there isnt. Every day (at least once) this thing's happening. just i have these.  I did what you said. :)

**Comment by NexiusTailer** [comment] 2022-09-16 18:13
I don't know what could be the cause then.

**Comment by recepilhanli** [comment] 2022-09-16 18:14
I'm working on it. If I get something new i will text here.

**Comment by AbdulOmarCR** [comment] 2022-09-18 00:51
Hello, I've recently updated Pawn.RakNet, and had the same problem, but it is not Nex-AC fault, idk why but since Pawn.RakNet v1.5.0 if you have an array index out of bounds it produces these problems.

You can test this by accessing an invalid array index, for example in a command:

`
new ErrorTest[MAX_PLAYERS]; //create this global array
`
`
CMD:errortest(playerid, params[])
{
      ErrorTest[playerid+MAX_PLAYERS];
      return true;
} //this command will access an invalid array index
`

**Comment by NexiusTailer** [comment] 2022-09-18 12:14
@AbdulOmarCR the thing is in that any such code must trigger crashdetect log at first, but @recepilhanli says there's no any of `[debug]` ones, only from Pawn.RakNet which is pretty weird. Anyway, since this is not really related to the anticheat as you mentioned, I'll wait for a couple of days for a final response from @recepilhanli if he found anything related the the real cause or not and then close the issue.

**Comment by AbdulOmarCR** [comment] 2022-09-18 18:43
I think he is not including crashdetect first in server.cfg, thats why it is not even loading crashdetect, but yes, i've tested this and it's something with Pawn.RakNet when there is an array index out of bounds.

**Comment by recepilhanli** [comment] 2022-09-19 20:43
I've already included it in server.cfg. i did what you guys said. That's kindda weird error. I've checked all of my gamemode but i found nothing. I'm still searching.
Fact: I havent touched my pawn.raknet scripts since 1 year.

**Comment by NexiusTailer** [comment] 2022-10-05 00:48
@recepilhanli did you found anything since the last checking?

**Closed** 2022-10-07 12:35 UTC
