### ISSUE TITLE
False detection on teleport

### ISSUE THREAD

**Issue by zXLiMiT-ToTAL** [NexiusTailer/Nex-AC#264] opened 2022-05-15 03:45 UTC
When a player is entering the vehicle as a passenger and the driver decides to teleport, (SetPlayerPos) the player who was entering the vehicle is falsely detected by the anti cheat.

[Nex-AC debug] Speed: 0, dist: 38.165164, dist set: 25000.000000

[Nex-AC debug] Dist: 3496.487792, dist set: 25000.000000, speed: 0, pos x, y, z: -1982.436279, 108.419189, 38.020820, old pos x, y, z: 1146.163330, -1452.606811, 15.903982

**Comment by NexiusTailer** [comment] 2022-05-15 09:54
Share the full anticheat logs (as I don't understand whom detected the first line and whom the second), and share the code so it can be possible to reproduce that.

**Comment by zXLiMiT-ToTAL** [comment] 2022-05-16 01:59
new tests
[Nex-AC debug] Dist: 2593.281494, dist set: 25000.000000, speed: 0, pos x, y, z: 2165.970703, 943.975830, 20.294466, old pos x, y, z: 1136.597045, -1436.250732, 15.796875
[Nex-AC] Suspicious player, ID 0. Reason code: 002 (2)
[Nex-AC debug] Dist: 3776.582275, dist set: 25000.000000, speed: 0, pos x, y, z: -1985.149169, 110.201644, 38.023704, old pos x, y, z: 1313.624389, -1728.295166, 13.594498
[Nex-AC] Suspicious player, ID 1. Reason code: 002 (2)
[Nex-AC debug] Dist: 2669.319824, dist set: 25000.000000, speed: 0, pos x, y, z: 2043.805175, 1006.954650, 21.517662, old pos x, y, z: 1397.871337, -1583.021728, 13.785035
[Nex-AC] Suspicious player, ID 1. Reason code: 002 (2)

CMD:lossantos(playerid)
{
    SetPlayerInterior(playerid, 0);
	SetPlayerVirtualWorld(playerid, 0);
	new vehicle = GetPlayerVehicleID(playerid);
    if(GetPlayerState(playerid) == 2)
	{
		SetVehiclePos(vehicle, 1396.1110+10, -1579.0890, 14.1103+10);
		SetVehicleZAngle(vehicle, 351.9701);
	}
	else
	{
		SetPlayerPos(playerid, 1396.1110, -1579.0890, 14.1103);
		SetPlayerFacingAngle(playerid, 351.9701);
	}
	SetCameraBehindPlayer(playerid);
	SendClientMessage(playerid, -1, "Los Santos");
	return 1;
}

**Comment by zXLiMiT-ToTAL** [comment] 2022-05-18 00:20
Any solution to this problem?

**Comment by NexiusTailer** [comment] 2022-05-19 11:47
Seems like its silent teleport bug which was fixed (on the server side) by RogueDrifter.
You can try it as [standalone include](https://github.com/RogueDriftout/Silent-teleport-bugfix-inc-) or as a part of [fixes.inc](https://github.com/pawn-lang/sa-mp-fixes) (FIX_SilentTeleport)

**Comment by zXLiMiT-ToTAL** [comment] 2022-05-21 04:15
Added include <fixes> and the problem continues.

#include <a_samp>
#include <fixes>
#include <nex-ac>

[Nex-AC debug] Dist: 4123.988769, dist set: 25000.000000, speed: 0, pos x, y, z: -1985.727905, 108.429412, 38.017169, old pos x, y, z: 2044.480346, 982.482238, 10.863789
[Nex-AC] Suspicious player, ID 1. Reason code: 002 (2)

**Comment by NexiusTailer** [comment] 2022-05-21 11:32
Which include order you have? Put your code in ``` if you can't display it by bare paste

**Comment by zXLiMiT-ToTAL** [comment] 2022-05-22 04:03
The order of the includes is like this:

```a_samp```
```fixes```
```nex-ac```

The code is the same as above.

**Comment by NexiusTailer** [comment] 2022-05-22 17:48
Try to include standalone silent-teleport fix after the anticheat (considering that fixes.inc will throw compile errors if it will be included not before anything that hooks samp functions, making it include after nex-ac will also be problematic).

**Comment by zXLiMiT-ToTAL** [comment] 2022-05-24 02:41
Even once it is included, the problem remains.
Tested the Fsbstp include, below and above include.

[Nex-AC debug] Dist: 4121.944824, dist set: 25000.000000, speed: 0, pos x, y, z: -1985.615234, 108.927459, 37.976825, old pos x, y, z: 2041.975708, 985.400268, 10.881518

Another test:
When the player tries to get on the bike, he is kicked and another nex-ac debug appears.

[Nex-AC debug] Veh model: 522, veh: 1, AFK time: 135, dist: 2616.471435

**Comment by NexiusTailer** [comment] 2022-05-30 10:47
As for the first issue, I found some time to check what exactly fixes and fsbstp do if it's not solving the problem and found out the reason: they consider silent teleport on driver's seat only, not passenger. You can propose to add passenger check as well in both libraries.

As for this:
```
[Nex-AC debug] Veh model: 522, veh: 1, AFK time: 135, dist: 2616.471435
```
I need more information about the case as usual.

**Closed** 2022-08-04 21:50 UTC
