### ISSUE TITLE
Code 004

### ISSUE THREAD

**Issue by Bt6K** [NexiusTailer/Nex-AC#325] opened 2024-08-07 11:59 UTC
Hello,

OpenMP 1.2.0.2670 server
SA-MP 0.3.7 R5 client

I've observed code `004 (1)` on my server quite a lot, in what in the cases I've observed are false-positives:

Here are some example logs from two different players:

```
[2024-08-07T12:31:02+0100] [Info] Player 2 has entered a vehicle!
[2024-08-07T12:31:06+0100] [Info] Player 2 has died!
[2024-08-07T12:31:08+0100] [Info] [Nex-AC debug] Entered veh: 0, veh: 30, entered seat: -1, seat: 0, veh model: 523, enter time: 6876
[2024-08-07T12:31:08+0100] [Info] [Nex-AC] Suspicion on the ID 2. Reason code: 004 (1)
[2024-08-07T12:31:08+0100] [Info] Player 2 has entered a vehicle!
[2024-08-07T12:31:08+0100] [Info] OnPlayerDisconnect(2)
[2024-08-07T12:31:08+0100] [Info] [part] hamood983234 has left the server (2:2)
```

```
[2024-08-07T12:38:51+0100] [Info] Player 3 has entered a vehicle!
[2024-08-07T12:40:46+0100] [Info] Player 3 has died!
[2024-08-07T12:40:47+0100] [Info] [Nex-AC debug] Entered veh: 0, veh: 1849, entered seat: -1, seat: 0, veh model: 522, enter time: 118067
[2024-08-07T12:40:47+0100] [Info] [Nex-AC] Suspicion on the ID 3. Reason code: 004 (1)
[2024-08-07T12:40:47+0100] [Info] Player 3 has entered a vehicle!
[2024-08-07T12:40:48+0100] [Info] OnPlayerDisconnect(3)
[2024-08-07T12:40:48+0100] [Info] [part] love1376 has left the server (3:2)
```

It's important to note it **doesn't** happen every time, I have **not** been able to work out exactly what causes it.

I was able to replicate the issue on a **blank gamemode** using the following:

https://github.com/openmultiplayer/qawno/blob/8f9f619531dc0c354bdcd889fe9975edb53f7b5d/gamemode.new
https://github.com/katursis/Pawn.RakNet/releases/tag/1.6.0-omp
https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc

What I find interesting is that in each case, moments after the death is recorded and Nex-AC triggers the kick, some debug code I added to `OnPlayerStateChange` triggers (i.e. the "has entered a vehicle!").

Any thoughts would be appreciated.

Many thanks

**Comment by NexiusTailer** [comment] 2024-08-08 09:29
Did you include weapon-config before nex-ac or after it?

**Comment by NexiusTailer** [comment] 2024-08-13 07:07
So, your client keep sending like he is in vehicle even after spawn.
Share the code from your gamemode which you use to spawn players in the case on the video. Did you also modified anything inside weapon-config.inc?

**Comment by NexiusTailer** [comment] 2024-08-13 08:42
I cannot reproduce this at the moment. The problem is in that your client for some reason does not stop sending vehicle sync even after he was spawned and he's not allowed to do so. But idk what can be the cause for this behaviour.

**Comment by NexiusTailer** [comment] 2024-08-16 07:34
I just tested it exactly under gamemode.new from omp server package and faced this issue.
First of all, the main anticheat code which is triggered is not 004, it's 048:
![image](https://github.com/user-attachments/assets/033b1c8b-a5a8-4f79-b15a-eb492645cfda)

and this reveal the issue itself: something goes wrong in omp server with changing player states when he dies (state `0`/`unknown` must be only passed when a player connecting, it cannot be in-game after he changed his state to any other). I still didn't figure out what causes such behaviour so that omp server sets player state 0 for a moment, but it should probably be addressed in the server repo.

**Comment by NexiusTailer** [comment] 2024-08-16 07:40
Disabling codes not a solution, just report the issue to omp server if you able to make a minimal reproducible example.

**Closed** 2024-08-16 07:42 UTC
